stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: "$VITE_API_BASE_URL"
  HEROKU_CLIENT_APP_NAME: "incite-client"

before_script:
  - |
    echo "Running as user: $(whoami)"
    # You can add more commands here if needed 

test_server:
  stage: test
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - rm -rf /root/.npm # Clear npm cache for the root user
    - npm ci 
    - npm test
  only:
    - main
    - /^feature\/.*$/ # Enable tests for feature branches

test_client: 
  stage: test
  image: docker:19.03.12 
  script:
    - apt-get update && \
      apt-get install -y \
        curl \
        gnupg \
        lsb-release && \
      curl -fsSL -o get_nodejs.sh https://deb.nodesource.com/setup_16.x && bash get_nodejs.sh && \
      apt-get install -y nodejs && \
      rm -rf get_nodejs.sh # Cleanup
    - cd client
    - npm ci 
    - npm test 

eslint_job:
  stage: test
  image: docker:19.03.12  
  script:
    # Install Node.js
    - apt-get update && \
      apt-get install -y \
        curl \
        gnupg \
        lsb-release && \
      curl -fsSL -o get_nodejs.sh https://deb.nodesource.com/setup_16.x && bash get_nodejs.sh && \
      apt-get install -y nodejs && \
      rm -rf get_nodejs.sh # Cleanup

    # Linting steps
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..." 
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/


build_client:
  stage: build
  script:
    - cd client
    - npm ci
    - npm run build 
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku: 
  stage: deploy
  image: docker:latest # Use Docker image
  services:
    - docker:dind # Enable Docker-in-Docker service
  variables:
    DOCKER_HOST: tcp://docker:2375/ # Use Docker daemon provided by dind service
    DOCKER_DRIVER: overlay2
    # Ensure DOCKER_TLS_CERTDIR is unset if issues arise with TLS
    # DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u bigadg -p $DOCKER_HUB_PASSWORD 
    - docker build -t bigadg/incite-server:latest . 
    - docker push bigadg/incite-server:latest
    - npm install -g heroku 
    - heroku container:login
    - heroku git:remote -a incite 
    - heroku container:push web -a incite
    - heroku container:release web -a incite
  only:
    - main

deploy_client_to_heroku:
  stage: deploy
  image: node:lts 
  before_script: 
    - nvm install 
    - nvm use 
  script:
    - npm install -g heroku 
    - heroku login  
    - heroku git:remote -a incite-client 
    - cd client 
    - npm ci 
    - npm run build
    - git add dist 
    - git commit -m "Deploying Vite build" 
    - git push heroku main:master 
  only:
    - main 