image: node:18.12.1 # Default Node.js version for consistency

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: "$VITE_API_BASE_URL"
  HEROKU_CLIENT_APP_NAME: "incite-client"

# Install Node modules once for efficiency 
before_script:
  - cd client
  - npm ci    

test_server:
  stage: test
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm test 
  only:
    - main
    - /^feature\/.*$/ 

test_client:
  stage: test
  script:
    - npm test 
  only:
    - main
    - /^feature\/.*$/ 

eslint_job:
  stage: test
  script:
    - echo "Linting Client..."
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm run lint
  only:
    - main
    - /^feature\/.*$/ 

build_client:
  stage: build
  script:
    - npm run build --verbose  
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:18.12.1  # Ensure consistency
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - |
      cd server
      npm install
      dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main

deploy_client_to_heroku:
  stage: deploy
  image: node:18.12.1 # Node.js for deployment step
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl 
    - dpl --provider=heroku --app=$HEROKU_CLIENT_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main