stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: "$VITE_API_BASE_URL"
  HEROKU_CLIENT_APP_NAME: "incite-client"

test_server:
  stage: test
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/ # Enable tests for feature branches

test_client:
  stage: test
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku: 
  stage: deploy
  image: node:lts 
  script:
    - npm install -g heroku # Install Heroku CLI
    - heroku login -i 
    - heroku git:remote -a $HEROKU_APP_NAME
    - cd server 
    - git push heroku main:master 
  only:
    - main 

deploy_client_to_heroku:
  stage: deploy
  image: node:lts 
  script:
    - npm install -g heroku 
    - heroku login -i 
    - heroku git:remote -a $HEROKU_CLIENT_APP_NAME
    - cd client 
    - git push heroku main:master
  only:
    - main 
