stages:
  - test
  - build
  - deploy

# Caching node_modules for efficiency
cache:
  paths:
    - client/node_modules/
    - server/node_modules/

test_server:
  stage: test
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - master

test_client:
  stage: test
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - master

eslint_job:
  stage: test
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - master

build_client:
  stage: build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/build/ # Ensure this path is correct for where your build artifacts are placed
  only:
    - master

deploy_server:
  stage: deploy
  script:
    - cd server
    - npm ci
    # Add server deployment commands here
  only:
    - master

deploy_client:
  stage: deploy
  script:
    - cd client
    # Add client deployment commands here
  only:
    - master
  dependencies:
    - build_client

# Customize the following as needed:
# - Deployment scripts depend on your hosting solution and should be added to deploy jobs
