stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: $VITE_API_BASE_URL
  HEROKU_CLIENT_APP_NAME: incite-client

test_server:
  stage: test
  image: node:16.20.0
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16.20.0
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_client_to_heroku:
  stage: deploy
  image: heroku/heroku:18
  script:
    - heroku login --apikey $HEROKU_API_KEY
    - heroku git:remote -a $HEROKU_CLIENT_APP_NAME
    - cd client
    - git init
    - git config user.email "you@example.com"
    - git config user.name "Your Name"
    - git add .
    - git commit -am "Deploy Client"
    - git push --force heroku master
  only:
    - main

deploy_server_to_heroku:
  stage: deploy
  image: heroku/heroku:18
  script:
    - heroku login --apikey $HEROKU_API_KEY
    - heroku container:login
    - docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web
    - heroku container:release web --app $HEROKU_APP_NAME
  only:
    - main
