stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  HEROKU_APP_NAME: incite
  HEROKU_API_KEY: $HEROKU_API_KEY
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  PORT: $PORT
  DB_NAME: InciteDB

test_server: 
  stage: test
  image: mongo:latest
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/ # Enable tests for feature branches

test_client:
  stage: test
  image: node:16
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/build/ # Changed from dist to build if you are using Create React App
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:16
  before_script:
    - npm install -g heroku # Install Heroku CLI globally
  script:
    - npm ci --prefix server # Install server dependencies
    - heroku --version
    - echo "$HEROKU_API_KEY" | heroku auth:token
    - heroku git:remote -a $HEROKU_APP_NAME
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    - git checkout main || true
    - git add -A || true # Add all changes from the repo root
    - git commit -am "Deploy to Heroku" || true
    - git push heroku `git subtree split --prefix server main`:main --force # Deploy server directory to Heroku
  only:
    - main
