stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/
    - extension/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME

test_server:
  stage: test
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/ # Enable tests for feature branches

test_client:
  stage: test
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/ # Adjusted from client/build to client/dist as you use Vite
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:latest # Use Node.js image since we're deploying a Node.js app
  script:
    - cd server
    - npm ci --only=production # Install only production dependencies
    - echo "web: npm start" > Procfile # Create a Procfile for Heroku
    - git init
    - git config user.email "bigadgaber@icloud.com"
    - git config user.name "Bigad Gaber"
    - git add .
    - git commit -m "Deploy to Heroku"
    - heroku git:remote -a $HEROKU_APP_NAME
    - git push heroku master --force
  environment:
    name: production
    url: https://$HEROKU_APP_NAME.herokuapp.com
  only:
    - main