stages:
  - test
  - build
  - deploy

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: $VITE_API_BASE_URL
  HEROKU_CLIENT_APP_NAME: $HEROKU_CLIENT_APP_NAME

cache:
  paths:
    - node_modules/
    - client/node_modules/
    - server/node_modules/

test_server:
  stage: test
  image: node:16.20.0
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:16.20.0
  script:
    - npm install -g heroku
    - heroku git:remote -a $HEROKU_APP_NAME
    - git add .
    - git commit -am "Deploy to Heroku"
    - git push heroku main
  only:
    - main

deploy_client_to_heroku:
  stage: deploy
  image: node:16.20.0
  script:
    - npm install -g heroku
    - heroku git:remote -a $HEROKU_CLIENT_APP_NAME
    - cd client
    - git init
    - git add .
    - git commit -am "Deploy client to Heroku"
    - git push heroku main
  only:
    - main