stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: $VITE_API_BASE_URL
  HEROKU_CLIENT_APP_NAME: $HEROKU_CLIENT_APP_NAME

before_script:
  - apt-get update && apt-get install -y ssh-client git
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "bigadgaber@icloud.com"
  - git config --global user.name "Bigad Gaber"

test_server:
  stage: test
  image: node:16.20.0
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16.20.0
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:16.20.0
  script:
    - git clone https://git.heroku.com/$HEROKU_APP_NAME.git heroku_deploy
    - rsync -av --exclude=node_modules --exclude=.git ./ heroku_deploy/
    - cd heroku_deploy
    - git add .
    - git commit -am "Deploy to Heroku"
    - git push heroku main
  only:
    - main

deploy_client_to_heroku:
  stage: deploy
  image: node:16.20.0
  script:
    - git clone https://git.heroku.com/$HEROKU_CLIENT_APP_NAME.git heroku_client_deploy
    - rsync -av --exclude=node_modules --exclude=.git ./client heroku_client_deploy/
    - cd heroku_client_deploy
    - git add .
    - git commit -am "Deploy client to Heroku"
    - git push heroku main
  only:
    - main
