stages: 
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  HEROKU_APP_NAME: incite
  HEROKU_API_KEY: $HEROKU_API_KEY
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  PORT: $PORT
  DB_NAME: InciteDB
  NODE_OPTIONS: "--max_old_space_size=4096"

test_server:
  image: node:16
  stage: test
  services:
    - mongo:latest
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  image: node:18.17.1
  stage: test
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  image: node:18.17.1
  stage: test
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:18.17.1
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  image: ruby:latest # Switching to a Ruby image for Heroku CLI compatibility
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y nodejs git
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku --version
    - echo "$HEROKU_API_KEY" | heroku auth:token --stdin
    - heroku git:remote -a $HEROKU_APP_NAME
    - cd server
    - git init
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    - git add .
    - git commit -am "Deploy to Heroku"
    - git push heroku master:main
  only:
    - main