stages:
  - test
  - build
  - deploy

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: $VITE_API_BASE_URL
  HEROKU_CLIENT_APP_NAME: $HEROKU_CLIENT_APP_NAME

cache:
  paths:
    - node_modules/
    - client/node_modules/
    - server/node_modules/

test_server:
  stage: test
  image: node:16.20.0
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:16.20.0
  script:
    # Install Heroku CLI without assuming global installation
    - npm install -g heroku
    # Setup Git configuration for Heroku deployment
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    # Initialize Heroku if not already done
    - heroku git:remote -a $HEROKU_APP_NAME
    # Ensuring we're on the correct branch and the repository is updated
    - git checkout main
    # Add all changes (including potential artifacts from previous stages)
    - git add -A
    # Commit changes with a CI-specific message
    - git commit -m "Deploying to Heroku via GitLab CI/CD" || echo "No changes to commit"
    # Push to Heroku
    - git push heroku main:master --force
  only:
    - main

deploy_client_to_heroku:
  stage: deploy
  image: node:16.20.0
  before_script:
    # Setup Git and Heroku configuration for Heroku deployment
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    - npm install -g heroku
    - heroku git:remote -a $HEROKU_CLIENT_APP_NAME
    # Navigate to client directory and initialize a Git repository for Heroku deployment
    - cd client
    - git init
    - git remote add heroku https://git.heroku.com/$HEROKU_CLIENT_APP_NAME.git
  script:
    # Add and commit all files in the client directory
    - git add -A
    - git commit -m "Deploying client to Heroku via GitLab CI/CD" || echo "No changes to commit"
    # Push the changes to Heroku
    - git push heroku master --force
  only:
    - main

