stages: 
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  HEROKU_APP_NAME: incite
  HEROKU_API_KEY: $HEROKU_API_KEY
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  PORT: $PORT
  DB_NAME: InciteDB
  # Increase memory limit for Node.js processes
  NODE_OPTIONS: "--max_old_space_size=4096"

test_server:
  image: node:16
  stage: test
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/test"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:18.17.1
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:18.17.1
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:18.17.1
  script:
    - apk add --no-cache bash git # Use apk for Alpine-based images or the equivalent for your base image
    - cd client
    - npm ci
    # Attempt a different approach to build if direct `npm run build` fails
    - npm run build || echo "Fallback command if build fails"
    - ls -lah dist # Verify build output
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  image: node:16
  stage: deploy
  script:
    - npm install -g heroku
    - heroku --version
    - echo $HEROKU_API_KEY | heroku auth:token --stdin
    - heroku git:remote -a $HEROKU_APP_NAME
    - cd server
    - git init
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    - git add .
    - |
      if git diff --cached --quiet; then
        echo "No changes to deploy. Exiting gracefully."
        exit 0
      else
        git commit -am "Deploy to Heroku"
        git push heroku master
      fi
  only:
    - main