stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  HEROKU_APP_NAME: incite
  HEROKU_API_KEY: $HEROKU_API_KEY
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  PORT: $PORT
  DB_NAME: InciteDB

test_server: 
  stage: test
  image: mongo:latest
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/ # Enable tests for feature branches

test_client:
  stage: test
  image: node:16
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:16
  script:
    - npm ci --prefix server # Install server dependencies
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku --version
    - echo $HEROKU_API_KEY | heroku auth:token --stdin # Authenticate with Heroku
    - heroku git:remote -a $HEROKU_APP_NAME --prefix server
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    - git add .
    - git commit -am "Deploy to Heroku"
    - git subtree push --prefix server heroku main
  only:
    - main