stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  HEROKU_APP_NAME: incite
  HEROKU_API_KEY: $HEROKU_API_KEY
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  PORT: $PORT
  DB_NAME: InciteDB

services:
  - mongo:latest

test_server: 
  stage: test
  image: node:16 # Use an image with Node.js
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/
  services:
    - name: mongo:latest
      alias: mongodb

test_client:
  stage: test
  image: node:16
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:16 # Use an image with Node.js
  before_script:
    - apk add --update git # If necessary, install git on the Alpine image
  script:
    - npm ci --prefix server
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku --version
    - heroku login -i
    - heroku git:remote -a $HEROKU_APP_NAME
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    - git add -A || true
    - git commit -m "Deploy to Heroku" || true
    - git push heroku `git subtree split --prefix server main`:main --force
  only:
    - main