stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  HEROKU_APP_NAME: incite
  HEROKU_API_KEY: $HEROKU_API_KEY
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  PORT: $PORT
  DB_NAME: InciteDB

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs npm
  - npm install -g heroku

test_server: 
  stage: test
  image: mongo:latest
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/ # Enable tests for feature branches

test_client:
  stage: test
  image: node:16
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/ # Changed back to dist for Vite
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  image: node:16
  stage: deploy
  script:
    - npx heroku --version
    - echo $HEROKU_API_KEY | npx heroku auth:token --stdin
    - npx heroku git:remote -a $HEROKU_APP_NAME
    - cd server
    - git init
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    - git add .
    - |
      git diff --cached --quiet || git commit -am "Deploy to Heroku"
      if [ $? -eq 0 ]; then
        git push heroku master
      else
        echo "No changes to deploy."
      fi
  only:
    - main
