stages:
  - test
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  HEROKU_APP_NAME: incite
  HEROKU_API_KEY: $HEROKU_API_KEY
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  PORT: $PORT
  DB_NAME: InciteDB
  # Define Docker image to use for building the client
  CLIENT_BUILD_IMAGE: node:18.17.1

before_script:
  - docker info

test_server:
  image: node:16
  stage: test
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/test"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:18.17.1 # Use the specific Node.js version that works locally
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:18.17.1 # Use the specific Node.js version that works locally
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run --rm -v $(pwd)/client:/app -w /app $CLIENT_BUILD_IMAGE /bin/sh -c "npm ci && npm run build"
    - mv client/dist/* public/ # Adjust this line according to where you want to move your build artifacts
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  image: node:16 # Use Node.js version 16 for server deployment tasks
  stage: deploy
  script:
    - npm install -g heroku
    - heroku --version
    - echo $HEROKU_API_KEY | heroku auth:token --stdin
    - heroku git:remote -a $HEROKU_APP_NAME
    - cd server
    - git init
    - git config --global user.email "bigadgaber@icloud.com"
    - git config --global user.name "Bigad Gaber"
    - git add .
    - if git diff --cached --quiet; then echo "No changes to deploy. Exiting gracefully."; exit 0; else git commit -am "Deploy to Heroku"; git push heroku master; fi
  only:
    - main