stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: $VITE_API_BASE_URL
  HEROKU_CLIENT_APP_NAME: incite-client

test_server:
  stage: test
  image: node:16.20.0
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16.20.0
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

# Simplified Heroku Deployment for the Server
deploy_server_to_heroku:
  stage: deploy
  image: node:16.20.0
  before_script:
    - npm install -g heroku
    - heroku --version
    - heroku login -i
  script:
    - heroku git:remote -a $HEROKU_APP_NAME
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git add .
    - git commit -m "Deploy to Heroku"
    - git push heroku main
  only:
    - main

# Using a Node.js image and leveraging Git for client deployment
deploy_client_to_heroku:
  stage: deploy
  image: node:16.20.0
  script:
    - npm install -g heroku
    - heroku login -i
    - heroku git:remote -a $HEROKU_CLIENT_APP_NAME
    - cd client
    - npm ci
    - npm run build
    - git init
    - git config user.email "you@example.com"
    - git config user.name "Your Name"
    - git add dist
    - git commit -m "Deploying Vite build"
    - git push heroku `git subtree split --prefix dist main`:refs/heads/main --force
  only:
    - main
