stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/
  key: ${CI_COMMIT_REF_SLUG}

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: "$VITE_API_BASE_URL"
  HEROKU_CLIENT_APP_NAME: "incite-client"

before_script:
  - echo "Running as user: $(whoami)"

test_server:
  image: node:16
  stage: test
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/ # Enable tests for feature branches

test_client:
  image: node:16
  stage: test
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  image: node:16
  stage: test
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  image: node:16
  stage: build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku: 
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - apk add --no-cache curl python3 py3-pip
    - pip install docker-compose
    - docker login -u bigadg -p $DOCKER_HUB_PASSWORD
    - docker build -t bigadg/incite-server:latest .
    - docker push bigadg/incite-server:latest
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku container:login
    - heroku git:remote -a $HEROKU_APP_NAME
    - heroku container:push web -a $HEROKU_APP_NAME
    - heroku container:release web -a $HEROKU_APP_NAME
  only:
    - main

deploy_client_to_heroku:
  image: node:16
  stage: deploy
  script:
    - npm install -g heroku
    - heroku login
    - heroku git:remote -a $HEROKU_CLIENT_APP_NAME
    - cd client
    - npm ci
    - npm run build
    - git init
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git add dist
    - git commit -m "Deploying Vite build to Heroku"
    - git push --force heroku `git subtree split --prefix dist master`:refs/heads/master
  only:
    - main