stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  PORT: 3001
  DB_NAME: InciteDB

test_server: 
  stage: test
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main

test_client:
  stage: test
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main

eslint_job:
  stage: test
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main

build_client:
  stage: build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/build/
    expire_in: 1 week  # Artifacts will be automatically deleted after one week

  only:
    - main

deploy_server:
  stage: deploy
  script:
    - cd server
    - npm ci
  only:
    - main

deploy_client:
  stage: deploy
  script:
    - cd client
  only:
    - main
  dependencies:
    - build_client

# Customize the following as needed:
# - Deployment scripts depend on your hosting solution and should be added to deploy jobs
