stages:
  - test
  - build
  - deploy

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: $VITE_API_BASE_URL
  HEROKU_CLIENT_APP_NAME: $HEROKU_CLIENT_APP_NAME

cache:
  paths:
    - node_modules/
    - client/node_modules/
    - server/node_modules/

test_server:
  stage: test
  image: node:16.20.0
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run lint
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku:
  stage: deploy
  image: node:16.20.0
  before_script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
    - git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git || true
  script:
    - git push heroku HEAD:main
  only:
    - main

deploy_client_to_heroku:
  stage: deploy
  image: node:16.20.0
  dependencies:
    - build_client
  before_script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
    - cd client
    - git init
    - git config user.email "bigadgaber@icloud.com"
    - git config user.name "Bigad Gaber"
    - git remote add heroku https://git.heroku.com/$HEROKU_CLIENT_APP_NAME.git || true
  script:
    - git add .
    - git commit -m "Deploy client to Heroku"
    - git push heroku HEAD:main -f
  only:
    - main

