stages:
  - test
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

variables:
  MONGO_ATLAS_PASSWORD: $MONGO_ATLAS_PASSWORD
  JWT_SECRET: $JWT_SECRET
  DB_NAME: InciteDB
  HEROKU_API_KEY: $HEROKU_API_KEY
  HEROKU_APP_NAME: $HEROKU_APP_NAME
  VITE_API_BASE_URL: "$VITE_API_BASE_URL"
  HEROKU_CLIENT_APP_NAME: "incite-client"

before_script:
  - echo "Running as user: $(whoami)"

test_server:
  stage: test
  image: node:16.20.0
  services:
    - mongo:latest
  variables:
    MONGO_URL: "mongodb://mongo:27017/$DB_NAME"
  script:
    - cd server
    - npm ci 
    - npm test
  only:
    - main
    - /^feature\/.*$/

test_client:
  stage: test
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm test
  only:
    - main
    - /^feature\/.*$/

eslint_job:
  stage: test
  image: node:16.20.0
  script:
    - echo "Linting Client..."
    - cd client
    - npm ci
    - npm run lint
    - echo "Linting Server..."
    - cd ../server
    - npm ci
    - npm run lint
  only:
    - main
    - /^feature\/.*$/

build_client:
  stage: build
  image: node:16.20.0
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 week
  only:
    - main
    - /^feature\/.*$/

deploy_server_to_heroku: 
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache npm # Ensure this line is properly nested as an array item
  script:
    - docker login -u bigadg -p $DOCKER_HUB_PASSWORD 
    - docker build -t bigadg/incite-server:latest . 
    - docker push bigadg/incite-server:latest
    - npm install -g heroku 
    - heroku container:login
    - heroku git:remote -a incite 
    - heroku container:push web -a incite
    - heroku container:release web -a incite
  only:
    - main

deploy_client_to_heroku:
  stage: deploy
  image: node:lts
  script:
    - npm install -g heroku 
    - heroku login  
    - heroku git:remote -a incite-client 
    - cd client 
    - npm ci 
    - npm run build
    - git add dist 
    - git commit -m "Deploying Vite build" 
    - git push heroku main:master 
  only:
    - main
