FROM node:16.20.0

WORKDIR /app

# Install Docker (adjust for your Linux distribution)
RUN apt-get update && apt-get install -y docker.io

COPY package*.json ./
RUN npm install

COPY . .

CMD ["npm", "start"]